set talk off
set echo off
set talk off
set safe off
set deli off
set dele on
set colo to
set scoreboard off
set escape on
set delimiter off
set conf off
set cons off
set date ansi
set safety off
set stat off
define window lpp1 at 0.000,0.000 size 28.000,80.000 ;
font "ËÎÌו",10 style "Bold"
activate window lpp1
*modify window screen font "ËÎÌו",12
public y,m,d,aa,bb,cc,dd,kk,gg,hh,ii,tt11,name