set talk off
store hh to hh0
set colo to w+/b+
zw=1
store dd to okd
store gg to okg
use \xsk\&y\fox1-99
count to ax for he0<>"  "

do while .t.
gg="xs"+chr(96+zw)
if zw>ax
store okd to dd
store okg to gg
use
exit
endif
use \xsk\&y\fox1-99
go zw
set colo to w+/bg+
@25,1 say "正在索引: "
set colo to n+/bg+
@25,11 say he0
*@13,39 say "   稍  等..."
use \xsk\&y\&gg-1
inde on t11 to \xsk\&y\&gg-1
use \xsk\&y\&gg-2
inde on t11 to \xsk\&y\&gg-2
use \xsk\&y\&gg-3
inde on t11 to \xsk\&y\&gg-3
*use \xsk\&y\&gg-4
*inde on t11 to \xsk\&y\&gg-4
*use \xsk\&y\&gg-5
*inde on t11 to \xsk\&y\&gg-5
*use \xsk\&y\&gg-6
*inde on t11 to \xsk\&y\&gg-6
zw=zw+1
enddo
use
keyb ""+CHR(13)
return
